/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.1.288.0
    Soft IP Version: 1.0.1
    2024 09 18 20:48:10
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_core (ref_clk_i, rst_n_i, lock_o, outcore_o, outglobal_o,
    outcoreb_o, outglobalb_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    output  lock_o;
    output  outcore_o;
    output  outglobal_o;
    output  outcoreb_o;
    output  outglobalb_o;
endmodule