create_clock -name {sys_clk} -period 25 [get_ports sys_clk]
create_clock -name {PLL/outcore_o} -period 4 [get_nets {PLL/outcore_o PLL/outglobal_o}]
create_clock -name {PLL/outcoreb_o} -period 8 [get_nets PLL/outcoreb_o]
create_clock -name {ls_clk} -period 16 [get_nets ls_clk]
create_clock -name {uls_clk} -period 32 [get_nets uls_clk]
#DISABLED# create_clock -name {uuls_clk} -period 64 [get_nets uuls_clk]
#DISABLED# create_clock -name {uuuls_clk} -period 128 [get_nets uuuls_clk]
create_clock -name {adc_conv_clk} -period 16 [get_ports adc_conv_clk]
#DISABLED# create_generated_clock -name {PLL/outcore_o} -source [get_ports sys_clk] -divide_by 4 -multiply_by 25 [get_nets {PLL/outcore_o PLL/outglobal_o}]
#DISABLED# create_generated_clock -name {PLL/outcoreb_o} -source [get_ports sys_clk] -divide_by 8 -multiply_by 25 [get_nets {PLL/outcoreb_o PLL/outglobalb_o}]
