

// TOOL:     vlog2tf
// DATE:     Fri Oct 18 17:43:56 2024
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   raw_meas_ram
// DESIGN:   raw_meas_ram
// FILENAME: raw_meas_ram_tf.v
// PROJECT:  VNA_FPGA_DSP
// VERSION:  2.0
// This file is auto generated by Radiant


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module raw_meas_ram_tf();

// Inputs
    reg wr_clk_i;
    reg rd_clk_i;
    reg rst_i;
    reg wr_clk_en_i;
    reg rd_en_i;
    reg rd_clk_en_i;
    reg wr_en_i;
    reg [23:0] wr_data_i;
    reg [11:0] wr_addr_i;
    reg [11:0] rd_addr_i;


// Outputs
    wire [23:0] rd_data_o;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    raw_meas_ram UUT (
        .wr_clk_i(wr_clk_i), 
        .rd_clk_i(rd_clk_i), 
        .rst_i(rst_i), 
        .wr_clk_en_i(wr_clk_en_i), 
        .rd_en_i(rd_en_i), 
        .rd_clk_en_i(rd_clk_en_i), 
        .wr_en_i(wr_en_i), 
        .wr_data_i(wr_data_i), 
        .wr_addr_i(wr_addr_i), 
        .rd_addr_i(rd_addr_i), 
        .rd_data_o(rd_data_o)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            wr_clk_i = 0;
            rd_clk_i = 0;
            rst_i = 0;
            wr_clk_en_i = 0;
            rd_en_i = 0;
            rd_clk_en_i = 0;
            wr_en_i = 0;
            wr_data_i = 0;
            wr_addr_i = 0;
            rd_addr_i = 0;
    end

endmodule // raw_meas_ram_tf