/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.1.288.0
    Soft IP Version: 2.0.0
    2024 10 20 10:25:14
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module adc_counter (clk_i, clk_en_i, aclr_i, q_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  aclr_i;
    output  [12:0]  q_o;
endmodule