/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.1.288.0
    Soft IP Version: 2.0.0
    2024 10 01 10:43:57
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module fir_shift_reg (clk_i, rst_i, clk_en_i, wr_data_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_i;
    input  clk_en_i;
    input  [11:0]  wr_data_i;
    output  [11:0]  rd_data_o;
endmodule