/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.1.288.0
    Soft IP Version: 1.0.0
    2024 09 18 11:27:20
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module spi_peripheral (spi1_miso_io, spi1_mosi_io, spi1_sck_io, spi1_scs_n_i,
    spi1_mcs_n_o, rst_i, ipload_i, ipdone_o, sb_clk_i, sb_wr_i, sb_stb_i,
    sb_adr_i, sb_dat_i, sb_dat_o, sb_ack_o, spi_pirq_o, spi_pwkup_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    inout  spi1_miso_io;
    inout  spi1_mosi_io;
    inout  spi1_sck_io;
    input  spi1_scs_n_i;
    output  [3:0]  spi1_mcs_n_o;
    input  rst_i;
    input  ipload_i;
    output  ipdone_o;
    input  sb_clk_i;
    input  sb_wr_i;
    input  sb_stb_i;
    input  [7:0]  sb_adr_i;
    input  [7:0]  sb_dat_i;
    output  [7:0]  sb_dat_o;
    output  sb_ack_o;
    output  [1:0]  spi_pirq_o;
    output  [1:0]  spi_pwkup_o;
endmodule